#include<stdio.h>
#include<string.h>

int main(){
	char texto[] = "LWNSOZBNWVWBAYBNVBSQWVWOHWDIZWRBBNPBPOOUWRPAWXAWPBWZWMYPOBNPBBNWJPAWWRZSLWZQJBNWIAXAWPBSALIBNXWABPIRYRPOIWRPQOWAIENBVBNPBPUSREBNWVWPAWOIHWOIQWABJPRZBNWFYAVYIBSHNPFFIRWVVBNPBBSVWXYAWBNWVWAIENBVESDWARUWRBVPAWIRVBIBYBWZPUSREUWRZWAIDIREBNWIATYVBFSLWAVHASUBNWXSRVWRBSHBNWESDWARWZBNPBLNWRWDWAPRJHSAUSHESDWARUWRBQWXSUWVZWVBAYXBIDWSHBNWVWWRZVIBIVBNWAIENBSHBNWFWSFOWBSPOBWASABSPQSOIVNIBPRZBSIRVBIBYBWRWLESDWARUWRBOPJIREIBVHSYRZPBISRSRVYXNFAIRXIFOWVPRZSAEPRIKIREIBVFSLWAVIRVYXNHSAUPVBSVWWUUSVBOICWOJBSWHHWXBBNWIAVPHWBJPRZNPFFIRWVV";
	int i;
	char troca[2];

/*	char ingles[] = "ETAOINSHRDLUCMWFYGPBVKJZXQ";
	char portugues[] = "AEOSRINDMTUCLPVGHQBFZJXKWY";
	char textoFre[] = " WBRSIVAPNOZHYUEXFDLJQTMKCG";
	
	for (i = 0; i < strlen(texto); ++i)
	{
		for (int j = 0; j < 26; ++j)
		{
			if(texto[i] == textoFre[j]){
				texto[i] = 	portugues[j];
				break;
			}
		}
	}

	printf("%s\n", texto);
*/

	while(1){
		printf("%s\n\n",texto );
		scanf("%s", &troca);
		
		for(i=0; i<strlen(texto);i++){
			if(texto[i] == troca[0]){
				texto[i] = troca[1];
			}
		}
	}

	return 0;
}