#include<stdio.h>
#include<string.h>

int main(){
	char texto[] = "LWNSOZBNWVWBAYBNVBSQWVWOHWDIZWRBBNPBPOOUWRPAWXAWPBWZWMYPOBNPBBNWJPAWWRZSLWZQJBNWIAXAWPBSALIBNXWABPIRYRPOIWRPQOWAIENBVBNPBPUSREBNWVWPAWOIHWOIQWABJPRZBNWFYAVYIBSHNPFFIRWVVBNPBBSVWXYAWBNWVWAIENBVESDWARUWRBVPAWIRVBIBYBWZPUSREUWRZWAIDIREBNWIATYVBFSLWAVHASUBNWXSRVWRBSHBNWESDWARWZBNPBLNWRWDWAPRJHSAUSHESDWARUWRBQWXSUWVZWVBAYXBIDWSHBNWVWWRZVIBIVBNWAIENBSHBNWFWSFOWBSPOBWASABSPQSOIVNIBPRZBSIRVBIBYBWRWLESDWARUWRBOPJIREIBVHSYRZPBISRSRVYXNFAIRXIFOWVPRZSAEPRIKIREIBVFSLWAVIRVYXNHSAUPVBSVWWUUSVBOICWOJBSWHHWXBBNWIAVPHWBJPRZNPFFIRWVV";
	int contador[26];
	int i = 0;
	for(i=0;i<26;i++){
		contador[i] = 0;
	}
	for(i=0; i<strlen(texto); i++){
		contador[texto[i]-'A']++;
	}

	double length = strlen(texto);
	for(i=0;i<26;i++){
		printf("%lf : -> %c\n", contador[i]/length,i+'A');
	}

	return 0;
}